### ISSUE TITLE
Sorting problem : New comment is always prepended to the comment list

### ISSUE THREAD

**Issue by ghisleouf** [FriendsOfSymfony/FOSCommentBundle#138]
I set default sorting to my config on date_asc, so comments are sorted from older to newer.

When I add a new comment, it is always prepended to the comments list, even if I changed default sorting.

Once I refresh the page, the new comment takes its good place.

**Comment by XWB** [comment]
We have resolved this issue with a javascript listener.

**Comment by longnd** [comment]
@XWB does that mean you added some events that would be fired on certain actions - example: once the user submit the comment form - so we can just catch that event to move the returned commentHtml anywhere we want ?

**Comment by XWB** [comment]
@longnd That would be correct.
