### ISSUE TITLE
I dont see the comments, problem with the script

### ISSUE THREAD

**Issue by Chrysweel** [FriendsOfSymfony/FOSCommentBundle#150]
I did all steps, but I can't see the script of comments.
But in my source code of page is the code of script.

``` js
// URI identifier for the thread comments
var fos_comment_thread_id = '/xxx/web/app_dev.php/api/threads/104/comments';

// Snippet for asynchronously loading the comments
(function() {
    var fos_comment_script = document.createElement('script');
    fos_comment_script.async = true;
    fos_comment_script.src = '/xxx/web/app_dev.php/js/35a8e64_comments_1.js';
    fos_comment_script.type = 'text/javascript';

    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(fos_comment_script);
})();
```

The number 104 is a integer.( the id of my post)
I included jquery-1.7.1.min.js

What am I doing wrong? Any idea? Thanks.

**Comment by MSoni05** [comment]
hey @merk is it necessary to include default  comment.js in layout ,as i already have in web/foscumment/js 
my console showing 

http://localhost/symfony/MySymPro/web/app_dev.php/api/threads/foo/comments?permalink=http%253A%252F%252Flocalhost%252Fsymfony%252FMySymPro%252Fweb%252Fapp_dev.php%252Fprofile%252F 500 ..some jquey error
