### ISSUE TITLE
What is the better way to show comments in flat view and not in tree view?

### ISSUE THREAD

**Issue by sensorario** [FriendsOfSymfony/FOSCommentBundle#159]
Hi! I do not understand how to show comments in flat mode. I've tried with this:

```
{% include 'FOSCommentBundle:Thread:async.html.twig' with { 'id': entity.id, 'view': 'flat' } %}
```

with no success. We have overwritten views/Thread/comments.html.twig from

```
{% set view = view|default('tree') %}
```

to

```
{% set view = 'flat' %}
```

This one is the only way? Can I caonfigure this stuff in yml?

**Comment by irmela** [comment]
If you load your comments asynchronously, you can override the comment.html.twig from
<code> {% set view = view|default('tree') %} </code>
to
<code> {% set view = 'flat' %} </code>
But this will apply to all comments on all pages.

If you don't load them asynchronously (see <a href="https://github.com/FriendsOfSymfony/FOSCommentBundle/blob/master/Resources/doc/10-other_ways_of_adding_comments_to_a_page.md">documentation</a>), you can do something like this in your template file:

<code>
{% include 'FOSCommentBundle:Thread:comments.html.twig' with {
            'comments': comments,
            'thread': thread,
            'view' : 'flat',
} %}
</code>

**Comment by blankse** [comment]
I create a PR to fix this https://github.com/FriendsOfSymfony/FOSCommentBundle/pull/626
