### ISSUE TITLE
Unable to override FOS\CommentBundle\Controller\ThreadController

### ISSUE THREAD

**Issue by umpirsky** [FriendsOfSymfony/FOSCommentBundle#225]
I want to customize voting system, so it shows number of upvotes and downvotes separatelly.

In order to achieve that I tried to override FOS\CommentBundle\Controller\ThreadController, but I failed, probably because it is rederenced with resource: FOS\CommentBundle\Controller\ThreadController in routing.yml.

What would be the proper way to override this controller?

**Comment by smarques** [comment]
What worked for me is using bundle inheritance for overriding the routing file.
