### ISSUE TITLE
Invalid URL Error

### ISSUE THREAD

**Issue by ping86** [FriendsOfSymfony/FOSCommentBundle#294]
Hellow,

When I use this bundle in firebug this error.

http://localhost/workspace/stf/web/app_dev.php/api/threads/2/comments?permalink=http%253A%252F%252Flocalhost%252Fworkspace%252Fstf%252Fweb%252Fapp_dev.php%252Fespana%252Fprovincias%252Fprovincia

Error message:

<ul>
    <li>sdfs\sdfsBundle\Entity\Thread.permalink:
    Please provide a valid url</li>
</ul>

The problem appears from this update: 

https://github.com/FriendsOfSymfony/FOSCommentBundle/commit/fc159236a953dec896c1bb07be2ed15eb944873b

We clean database, delete all tables, reinstall the bundle and the error continues.

Does anyone know how to fix it?

Thanks.

**Comment by roundge** [comment]
Hi there

I got the same problem, Firebug error : 
```http://_symfony.dev/admin/api/threads/event-30/comments   400 Bad Request```

The request `http://_symfony.dev/admin/api/threads/event-30/comments?permalink=http%253A%252F%252F_symfony.dev%252Fadmin%252Fe%252Fformation%252F30%252Finscriptions%252F` shows :  
`Object(Project\AppBundle\Entity\Thread).permalink: Please provide a valid url`

My configuration : 
```
friendsofsymfony/comment-bundle      v2.0.8
friendsofsymfony/rest-bundle         1.7.2 
symfony/symfony                      v2.7.7
doctrine/dbal                        v2.5.2
....
Php : 5.6.14-0+deb8u1
nginx version: nginx/1.6.2
```

The workaround adding suffix to the localhost address doesn't work for me. :( Any idea ?

**Comment by roundge** [comment]
hummm. It always seems to be a Symfony validator problem. If I comment the 'url' constraint in 
`FOS/CommentBundle/Resources/config/validation.xml`
it works! 

```xml
            <!-- <constraint name="Url">
                <option name="message">Please provide a valid url</option>
                <option name="groups">
                    <value>NewThread</value>
                </option>
            </constraint> -->
```
related to symfony issue https://github.com/symfony/symfony/issues/3207  again ?
