### ISSUE TITLE
Possibility to REALLY remove a comment

### ISSUE THREAD

**Issue by janimattiellonen** [FriendsOfSymfony/FOSCommentBundle#307]
From what I learned from browsing the code, you cannot remove a comment from the database. It is only flagged as removed.

At least I could not find any call to em->remove().

I suggest a way to remove comments marked as deleted is to be created. A command class could be created that traverses the database and looks for comments with the state 1 (DELETED) and removes those.

Before such a feature is to be created, it needs to be decided, what happens to all child comments. Will they also be removed? Or should their owner just be reset?

This command class would then be executed either manually using SF2 console or by executing it with the help of cron.

Additionally there could also be a "Actually remove this comment" button (with a better naming) for those roles that have the permission to remove comments.

**Comment by XWB** [comment]
You can always make an event listener and remove anything you want to remove.
