### ISSUE TITLE
using additional javascript for edit form fields

### ISSUE THREAD

**Issue by dleute** [FriendsOfSymfony/FOSCommentBundle#309]
I hooked into the js triggers to implement pagedown markdown processor for comments.

pagedown needs a js snippet to provide the edit buttons and the markdown preview.

I hooked into fos_comment_load_thread and fos_comment_show_form. That way the original post form works as do replies.

However, edits don't load the editor because there is no JS hook for that. I tried embedding the JS in the result (through a custom field widget extension for textarea). But It looks like script tags are sanitized by the ajax.

Is there a way currently to hook into the edit form for js? If not, should I submit a pull request with a new trigger fos_comment_edit_form implemented here:

FOS_COMMENT.thread_container.on('click',
                '.fos_comment_comment_edit_show_form',
                function(e) {
                    var form_data = $(this).data();
                    var that = this;

                    FOS_COMMENT.get(
                        form_data.url,
                        {},
                        function(data) {
                            var commentBody = $(that).parent().next();

                            // save the old comment for the cancel function
                            commentBody.data('original', commentBody.html());

                            // show the edit form
                            commentBody.html(data);
                        }
                    );
                }

Is that the option?

**Comment by XWB** [comment]
We can always add additional events, feel free to submit a PR.
