### ISSUE TITLE
Add field to comment

### ISSUE THREAD

**Issue by fabio983** [FriendsOfSymfony/FOSCommentBundle#334]
Hello everyone,
in my project I have the need to add a custom field to a comment.
Is there an easy way to do this ?

What I'm try to achieve is that when someone sends a comment it also has to populate this new mandatory field which will be persisted in the db.

I looked in the documentation but didn't find a clue...

Thanks.

**Comment by edgeeffect** [comment]
Just making this a little more confusing.
Would it be possible to add an additional field as described here and have comments on one part of the site ignore it.
I'm thinking about using it for ordinary comments on blog pages, but then have an additional field (5-star rating) for comments (reviews) on product pages.
