### ISSUE TITLE
templating: metas, body and reply (not replies/children) inside a div

### ISSUE THREAD

**Issue by tfernandez** [FriendsOfSymfony/FOSCommentBundle#381]
Hi,

Firstly, thanks for this great work, the comment bundle is being very usefull for me :)

I would suggest change the default comment template and put the divs "metas, body and reply (not replies) inside an unique div, now the comment template looks like:

    <div class="fos_comment_comment_metas">...</div>
    <div class="fos_comment_comment_body">...</div>
    <div class="fos_comment_comment_reply">...</div>
    <div class="fos_comment_comment_replies">...</div>

And keep the fos_comment_comment_replies div outside. The container div could be called (for example) fos_comment_comment_content. It will look like this:

    <div class="fos_comment_comment_content">...
        <div class="fos_comment_comment_metas">...</div>
        <div class="fos_comment_comment_body">...</div>
        <div class="fos_comment_comment_reply">...</div>
    </div>
    <div class="fos_comment_comment_replies">...</div>

This change would allow decorate all the content of only one comment without tricks and without affecting the comment children, for example a simple solid background color with rounded corners.

I know I can override the template, but I like to keep the templates synced with the master one unless it is absolutely necessary

I think it would be usefull for everyone, but maybe I'm wrong :)

Thanks,
Tomás

**Comment by XWB** [comment]
Feel free to submit a PR.
