### ISSUE TITLE
Extending FOSCommentBundle

### ISSUE THREAD

**Issue by meskis** [FriendsOfSymfony/FOSCommentBundle#388]
Hi,

I am trying to extend FOS Comment bundle and I'm receiving:
"Unable to generate a URL for the named route "fos_comment_get_threads" as such route does not exist."

Any ideas?

**Comment by chiqui3d** [comment]
@stof 
No solutions for extending the routing and so to extend the bundle?

**Comment by XWB** [comment]
Please check out the Symfony documentation https://symfony.com/doc/current/bundles/override.html
