### ISSUE TITLE
Divide method getThreadCommentsAction

### ISSUE THREAD

**Issue by Gemorroj** [FriendsOfSymfony/FOSCommentBundle#394]
Divide method getThreadCommentsAction ( https://github.com/FriendsOfSymfony/FOSCommentBundle/blob/master/Controller/ThreadController.php#L380 ) several smaller methods.
To add pagination I override methods getThreadCommentsAction. It is quite a lot of code that need to be duplicated in the overriding method. Although, I just need to pass a page number next to comment manager.

**Comment by XWB** [comment]
Feel free to submit a PR.
