### ISSUE TITLE
FOSCommentBundle : ServiceNotFoundException:

### ISSUE THREAD

**Issue by Aurelien-Maire** [FriendsOfSymfony/FOSCommentBundle#403]
Hi I try to install FOSComment.

After do all step in setup manual, I have this debug message. 

ServiceNotFoundException: The service "fos_comment.listener.comment_spam" has a dependency on a non-existent service "%fos_comment.spam_detection.comment%".

Thank for your help

**Comment by n1c01a5** [comment]
Can you give your configuration of this bundle?
