### ISSUE TITLE
Erreur 500

### ISSUE THREAD

**Issue by otherprod** [FriendsOfSymfony/FOSCommentBundle#409]
Hi, Bonjour,

j'ai un soucis avec le bundle de commentaire, j'ai suivi pas à pas les étapes d'installation du bundle, sans succès, quelque soit la méthode employée j'arrive tjs avec cette satanée erreur 500 lors du chargement de app_dev.php/api/threads/1/comments?permalink=lepermalink

En affichant directement cette page j'obtiens ceci: 

[Semantical Error] line 0, col 67 near 't WHERE t.id': Error: Class Vdj\VideoBundle\Entity\Comment has no association named thread
500 Internal Server Error - QueryException
1 linked Exception: QueryException »

et la requête auquelle cela fait référence est celle ci: 

 [1/2] QueryException: SELECT c FROM Vdj\VideoBundle\Entity\Comment c INNER JOIN c.thread t WHERE t.id = :thread ORDER BY c.ancestors ASC

J'ai essayé avec deux types differents de mapping, yaml et xml en définissant ceci dans el fichier config.yml à chaque fois, rien n'y fait.

J'ai suivi la documentation pas à pas et en essayant avec strictement les même fichiers et avec des fichiers différents, j'arrive tjs à cette erreur 500, merci de m'éclairer, cela fait plusieurs que je suis dessus et je vais craquer :)

**Comment by onnlinetool** [comment]
========>>>>>>>>>>>> Telecharger Crack ici

http://bit.ly/2nZwD1t

http://bit.ly/2nZwD1t

http://bit.ly/2nZwD1t

http://bit.ly/2nZwD1t

http://bit.ly/2nZwD1t

http://bit.ly/2nZwD1t

http://bit.ly/2nZwD1t

http://bit.ly/2nZwD1t

http://bit.ly/2nZwD1t
