### ISSUE TITLE
problem with foscommentbundle

### ISSUE THREAD

**Issue by monbassam** [FriendsOfSymfony/FOSCommentBundle#415]
Hello,
I have successfully installed the foscommentbundle in my symfony project. But the comment box is not displayed in my page.
However I can see the javascript downloaded in my page.
<script type="text/javascript">
// thread id
var fos_comment_thread_id = 'foo';

// api base url to use for initial requests
var fos_comment_thread_api_base_url = '/mulanga/web/app_dev.php/api/threads';

// Snippet for asynchronously loading the comments
(function() {
    var fos_comment_script = document.createElement('script');
    fos_comment_script.async = true;
    fos_comment_script.src = '/mulanga/web/app_dev.php/js/35a8e64_comments_1.js';
    fos_comment_script.type = 'text/javascript';

    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(fos_comment_script);
})();
</script>

I have so include the jQuery 1.9 and I get 35a8e64_comments_1.js with the command app\console assetic:dump

Thanks to help me

**Comment by XWB** [comment]
We need a bit more information. I'm closing this one, feel free to open a new ticket if you need further support.
