### ISSUE TITLE
Please provide more detailed and correct documentation

### ISSUE THREAD

**Issue by todstoychev** [FriendsOfSymfony/FOSCommentBundle#424]
Please provide more detailed and correct documentation about the installation steps. There is as lots of stuff in the instructions that is missing. For example: to make FOSCommentBundle work you also need to activate FOS\RestBundle\FOSRestBundle() in Symfony's AppKernel.php. This step is missing!

**Comment by XWB** [comment]
There's always room for improvements. Feel free to make some suggestions (or even better: open a PR).
