### ISSUE TITLE
Can anybody add some animation to Fosuserbundle when loading and submitting

### ISSUE THREAD

**Issue by seekmas** [FriendsOfSymfony/FOSCommentBundle#433]
it has no status to display when user clicks submit button , it causes people double click or more click . thk~

**Comment by XWB** [comment]
It's quite easy:

```js
$('#fos_comment_thread')
    .on('fos_comment_add_comment', hideAnimation)
    .on('fos_comment_before_load_thread', showAnimation)
    .on('fos_comment_load_thread', hideAnimation)
    .on('fos_comment_submitting_form', showAnimation);

function showAnimation()
{
    // show a loading icon
}

function hideAnimation()
{
    // hide the loading icon
}
```

**Comment by esmedo** [comment]
Sheers guy, i will try it later. :)

**Comment by esmedo** [comment]
Hi,
I try that

	$(function () {
		jQuery(document).ready(function() { 
			$("#submitconseil").click(function () {
				$(".loadernotif").show();
				$(".loadernotif").html('<img src="../../../web/images/ajax-loader.gif" />');
			});
			.on('fos_comment_new_comment', function (event, data) {
				$(".loadernotif").show();
			});
		});
	});
The loader appear but doesn't disapear. :s

I don't really know what to put to start the line 
    (???).on('fos_comment_new_comment', function (event, data) {

Some help... ? :)
