### ISSUE TITLE
Update comments after closing or opening a thread

### ISSUE THREAD

**Issue by iBet7o** [FriendsOfSymfony/FOSCommentBundle#434]
After close or open a thread there is an error in the url for comments.
![error_get_comments](https://cloud.githubusercontent.com/assets/590235/2887903/4ac2fae0-d502-11e3-9612-dc9df7d6131a.png)
The error is showing
```
No route found for "GET /mi-admin/proyecto/313/undefined/proyecto_313/comments"
```

If I define a value to variable fos_comment_thread_api_base_url
```
var fos_comment_thread_api_base_url = '/web/app_dev.php/api/threads';
```
when you update the thread does not show the buttons to manage

Before closing the thread
![before](https://cloud.githubusercontent.com/assets/590235/2888025/d5dcaa12-d503-11e3-8f45-6d57cef19d3d.png)

After closing the thread
![after](https://cloud.githubusercontent.com/assets/590235/2888030/e337a5b8-d503-11e3-9f51-177d2e3bc9d5.png)

**Comment by XWB** [comment]
Reloading the comment tree will show the correct buttons.
