### ISSUE TITLE
Voting doesn't work in Symfony 2.5

### ISSUE THREAD

**Issue by perk11** [FriendsOfSymfony/FOSCommentBundle#440]
Since ExecutionContext used in voting is deprecated in Symfony 2.5, votes now get instance of LegacyExecutionContext instead, this breaks the voting.

This is the error I get when trying to vote:

 Catchable Fatal Error: Argument 1 passed to FOS\CommentBundle\Model\Vote::isVoteValid() must be an instance of Symfony\Component\Validator\ExecutionContext, instance of Symfony\Component\Validator\Context\LegacyExecutionContext given in /var/www/vendor/friendsofsymfony/comment-bundle/FOS/CommentBundle/Model/Vote.php line 90 (500 Internal Server Error)

Pull request fixing this: https://github.com/FriendsOfSymfony/FOSCommentBundle/pull/441

**Comment by n1c01a5** [comment]
Can you close this issue if it's fixing?

**Comment by perk11** [comment]
PR wasn't merged though.

**Comment by XWB** [comment]
PR has been merged.
