### ISSUE TITLE
No active maintainer

### ISSUE THREAD

**Issue by merk** [FriendsOfSymfony/FOSCommentBundle#442]
We're seeking someone who might be willing to help out with tickets, PRs and general maintenance of this bundle.

**Comment by abhinavkumar940** [comment]
I can help

**Comment by n1c01a5** [comment]
Me too

**Comment by deralex** [comment]
I would also apply for the role as a maintainer of this bundle.

**Comment by BallisticPain** [comment]
Is this being maintained again? I see this issue is closed yet there hasn't been any updates but there are several PRs. Also the documentation is notating this as an unmaintained bundle.

**Comment by stephanvierkant** [comment]
Any news on this? According to kpnbundles.com there is still no active maintainer: http://knpbundles.com/FriendsOfSymfony/FOSCommentBundle.

**Comment by Ener-Getick** [comment]
This bundle is not actively developped but receives bug fixes and small improvements mostly merged by @XWB.

**Comment by Ener-Getick** [comment]
In fact our biggest need is not mergers but people reporting issues, submitting pull requests and commenting the one of others ☺
