### ISSUE TITLE
Translation of validation.xml

### ISSUE THREAD

**Issue by esmedo** [FriendsOfSymfony/FOSCommentBundle#444]
Hi guys,

When i put a message too short, i have the error message: "the message is too short". Wich is not so bad. :)

What is a problem is that it is in english  which is not the current local i'm using (fr). I've seen the file validation.xml where the error message are doesn't seem to be translated. 

How can i do to translate it ? I am on the wrong way ? :)

Thank you

**Comment by n1c01a5** [comment]
Have you tried override ```validation.xml```?

**Comment by XWB** [comment]
You should overwrite translation/validation file.
