### ISSUE TITLE
Access properties of a comment after vote

### ISSUE THREAD

**Issue by Don87** [FriendsOfSymfony/FOSCommentBundle#450]
Hi, I would like to notify a FOSuser when his/her comment has just been voted on. I plan to send a AJax request after a vote. I have read Step 13: Hooking into the JS code but have struggled to accomplish this.

### fos_comment_vote_comment( data )

Triggered when the the request about voting a comment succeeds.

 - data: data sent to the server with the request.

I wish to access, in order of utmost importance, the id of the user who made comment, the vote value (up or down) and possibly the comment id. Any help is very much appreciated, thanks!

**Comment by n1c01a5** [comment]
To access the id of the user, you can use the global variable {{ app.user }} or maybe {{ app.security.user }} in the view.

**Comment by Don87** [comment]
@XWB Why is this closed?

@n1c01a5 
Thanks for your response, but I am afraid it is not working. Let me explain.

I have a page where I load the comments using the suggested method {% include 'FOSCommentBundle:Thread:async.html.twig' with {'id': 'foo'} %}

On this page I wish to launch an ajax request to a url which will lead me to a symfony controller where I will manipulate this data. I am using twig as my templating engine.

According to the docs, I can use these two methods
$(document).on('fos_comment_new_comment', function (event, data) {
-----
}

$(document).on('fos_comment_vote_comment', function (event, data) {
----
}

I wish to pass variables such as the comment id or comment body or voted on comment id but it does not work, if I use {{ comment.id }} I get this error

Variable "comment" does not exist

How can I get these value, if I can at least get the id's then I can launch a query in the controller for the rest of the data although it would be perfect to get these values directly and post them in an ajax request.

Somebody... anybody?
