### ISSUE TITLE
Does FOSCommentBundle support custom entity class?

### ISSUE THREAD

**Issue by jamescheng16** [FriendsOfSymfony/FOSCommentBundle#453]
I'm new to the FOSCommentBundle, I have a question, Does FOSCommentBundle support custom entity class? 

I added a custom entity into a comment entity like :

class PointComment extends BaseComment implements SignedCommentInterface, VotableCommentInterface
{

    /**
     * @ORM\ManyToOne(targetEntity="SomeBundle\Entity\Point", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $point;

Can I make a comment and link this comment to a custom entity with the relation ManyToOne, If the answer is YES, how to pass the id of my entity(Point) from the View of FOSComment to my controller.

Thanks a lot.

**Comment by n1c01a5** [comment]
I think you must use the events. See how ```author``` is defined with the EventListener: https://github.com/FriendsOfSymfony/FOSCommentBundle/blob/master/EventListener/CommentBlamerListener.php

**Comment by XWB** [comment]
See above.
