### ISSUE TITLE
Can I disable ajax?

### ISSUE THREAD

**Issue by Slowwie** [FriendsOfSymfony/FOSCommentBundle#455]
Hey Guy´s, 

is there a simple way to disable ajax in fosCommentBundle. (For debugging issues)

Greetings Michael

**Comment by n1c01a5** [comment]
You can disable javascript in your browser.
In firefox, tape ```about:config``` and change the variable ```javascript.enabled``` to ```false```.

**Comment by XWB** [comment]
Disabling javascript can be done in the browser indeed.
