### ISSUE TITLE
Vote model isVoteValid method deprecated call for Symfony > 2.4

### ISSUE THREAD

**Issue by varloc2000** [FriendsOfSymfony/FOSCommentBundle#458]
Hello!

In master branch composer allows symfony dependency up to 3.0 version but accordingly with [Changelog](https://raw.githubusercontent.com/symfony/symfony/master/UPGRADE-3.0.md) method addViolationAt removed science 2.5 version. 
http://symfony.com/doc/2.5/cookbook/validation/custom_constraint.html#class-constraint-validator

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSCommentBundle/pull/470

**Comment by XWB** [comment]
Fixed in https://github.com/FriendsOfSymfony/FOSCommentBundle/pull/470
