### ISSUE TITLE
the view FOSComment  to the Vendor transferring  in src 

### ISSUE THREAD

**Issue by willkoua** [FriendsOfSymfony/FOSCommentBundle#461]
hello,
sorry i don't speak english correctly.
I would like to change the appearance of the feedback form without changing it directly into the vendor. How can I do for export views in the src?

**Comment by XWB** [comment]
You can override the template.

http://symfony.com/doc/current/cookbook/bundles/inheritance.html#overriding-resources-templates-routing-etc
http://symfony.com/doc/current/book/templating.html#overriding-bundle-templates
