### ISSUE TITLE
acl_roles: delete comment but not edit it

### ISSUE THREAD

**Issue by Xyr2** [FriendsOfSymfony/FOSCommentBundle#462]
Hey,

I want an admin user to be able to delete comments, but not to edit them.
Edit and delete logic seems to be connected anyhow. If I don't set 'edit' to ROLE_ADMIN too, the admin user sees a delete button, but nothing happens if he clicks it.

Unfortunately I couldn't figure out where this happens. Do you have an idea?

**Comment by Xyr2** [comment]
I found it. In the AclCommentManager.php in the saveComment function I changed:
```php
if (!$newComment && !$this->commentAcl->canEdit($comment)) {
    throw new AccessDeniedException();
}
```

to:
```php
if (!$newComment && !($this->commentAcl->canEdit($comment) OR $this->commentAcl->canDelete($comment))) {
    throw new AccessDeniedException();
}
```

**Comment by XWB** [comment]
:+1:
