### ISSUE TITLE
DateSorting not detecting same date correctly.

### ISSUE THREAD

**Issue by raulferras** [FriendsOfSymfony/FOSCommentBundle#469]
`DateSorting` class is comparing dates of the comment with `===` to check for equality. This will always return false even if dates are the same because `===` will not check the properties of the object but if the objects are in fact the same.

**Comment by XWB** [comment]
You are right.

```php
if ($a->getCreatedAt() === $b->getCreatedAt())
```

Should become something like

```php
if ($a->getCreatedAt()->getTimestamp() === $b->getCreatedAt()->getTimestamp())
```

Suggestions are welcome.

**Comment by XWB** [comment]
Have a look https://github.com/FriendsOfSymfony/FOSCommentBundle/pull/471

**Comment by raulferras** [comment]
I think a simple `==` would suffice as stated in: http://stackoverflow.com/a/961116/111065 and here http://php.net/manual/en/language.oop5.object-comparison.php
This avoids checking actually if instances are the same and not its values.  
Other comparisons were already ok (<)

**Comment by XWB** [comment]
@raulferras I've made some changes, have a look again.

**Comment by raulferras** [comment]
Looks great to me :)

**Comment by XWB** [comment]
Fixed https://github.com/FriendsOfSymfony/FOSCommentBundle/commit/45ae23fa89bebe8949eae25c02d84b251119d5a8
