### ISSUE TITLE
German translation wrong

### ISSUE THREAD

**Issue by KableCH** [FriendsOfSymfony/FOSCommentBundle#476]
While playing arround with this bundle, after completing this step https://github.com/FriendsOfSymfony/FOSCommentBundle/blob/master/Resources/doc/7-adding_role_based_acl_security.md I noticed that the german tranlation for the key 'fos_comment_comment_delete' is wrong. It is "Kommentar bearbeiten", which means "edit comment" but it should be "Kommentar löschen".

**Comment by XWB** [comment]
Fixed in https://github.com/FriendsOfSymfony/FOSCommentBundle/commit/cfe7865a027c9e1f95b7165c8e9283c49632011c

Thanks.
