### ISSUE TITLE
 [enhancements] support microblogging features

### ISSUE THREAD

**Issue by cazzoo** [FriendsOfSymfony/FOSCommentBundle#480]
Hello!

I'm using FOSCommentBundle "as is" for now and I'm wondering if you plan to implement some micro-blogging features such images, links or such?

I tought to get it working on my setup but I'm too busy right now on my site development to get in that features..

Regards

**Comment by tarjei** [comment]
You can easily do this yourself by changing the comment textarea from a simple textfield to an htmlfield and then supporting any of the features you want in your WYSIWIG editor of choice. No need to change anything in the commentbundle for that :P
