### ISSUE TITLE
Integrate Pipeline Parser into FOSCommentBundle

### ISSUE THREAD

**Issue by smilesrg** [FriendsOfSymfony/FOSCommentBundle#490]
It's good idea to integrate functionality for pipeline parsing that I did in this bundle:

https://github.com/smilesrg/PipelineParserBundle

**Comment by tarjei** [comment]
I think the parser bundle you wrote looks interesting. How about you suggest a PR for documentation on how to use it with FOSCommentBundle? Or are you interested in maintaining the functionalty as part of the bundle?

**Comment by smilesrg** [comment]
I think the parser I wrote should be integrated into FOSCommentBundle. I'll create a PR as soon as I have a free time. Of course, I can maintain this functionality as a part of the bundle.

**Comment by smilesrg** [comment]
https://github.com/FriendsOfSymfony/FOSCommentBundle/pull/579

**Comment by smilesrg** [comment]
@tarjei please look at my PR

**Comment by smilesrg** [comment]
#606

**Comment by XWB** [comment]
Merged, thanks!
