### ISSUE TITLE
Duplicated comments created when clicking many time on the send button

### ISSUE THREAD

**Issue by LeoBenoist** [FriendsOfSymfony/FOSCommentBundle#493]
Hi,

When a user write a comment and click many times on the Send button the Ajax post request are duplicated resulting in the creation of duplicated comments.

Usually to prevent this the submit button could be disabled and the form submit could be blocked until the first ajax request has been completely processed. 

Do you have any already in place solution to prevent that ?

**Comment by Ananas85** [comment]
UP

**Comment by Ananas85** [comment]
I have made a solution:

``` javascript
(function ($) {
    var comment = {};

    comment.construct = function () {
        comment.formSubmitHandler();
        comment.commentAddedHandler();
    };

    comment.commentAddedHandler = function () {
        $(document).on('fos_comment_add_comment', function()
        {
            $('.fos_comment_submit > input[type=submit]').removeAttr("disabled");
        });
    };

    comment.formSubmitHandler = function () {
        $(document).on('fos_comment_submitting_form', function()
        {
            $('.fos_comment_submit > input[type=submit]').attr("disabled", "disabled");
        });
    };

    comment.construct();
})(jQuery);
```

**Comment by The-Don-Himself** [comment]
+1 on this

@Ananas85 I would like to test your solution, where should someone place this code? In the base template? When you load the comments via twig? Or should one override some default FOSComment File?

**Comment by Alphanumerix** [comment]
The-Don-Himself: According to this https://github.com/FriendsOfSymfony/FOSCommentBundle/blob/master/Resources/doc/13-hooking_into_the_js_code.md you can put Ananas85's code anywhere, where it will be executable, for example in web/js/app.js or web/script.js, or even in <script> tag. 
Just don't forget it should be under tag with jQuery path in src.

**Comment by Ananas85** [comment]
Hi, sorry to answer only today, as @Alphanumerix said you can put it where you want, the link given by him would be helpful :)
