### ISSUE TITLE
Please release 2.0.8 :)

### ISSUE THREAD

**Issue by tarjei** [FriendsOfSymfony/FOSCommentBundle#504]
Hi, It would be just swell if I could install Commentbundle with JMS Serializer 1.x. Would it be possible to push out a new release quite soon?

**Comment by XWB** [comment]
Done :)

**Comment by tarjei** [comment]
Tanks a bundle!

2015-11-16 9:58 GMT+01:00 Karel <notifications@github.com>:

> Done :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FriendsOfSymfony/FOSCommentBundle/issues/504#issuecomment-156959286>
> .
>



-- 
__________________
Tarjei Huse
Mobil: 920 63 413
