### ISSUE TITLE
Comments not being displayed with mongodb

### ISSUE THREAD

**Issue by ajeetvarma** [FriendsOfSymfony/FOSCommentBundle#507]
I have installed the bundle according to the documentation and all the comments are saving in the database but posted comments with new comment form is not being displayed . only numbers of comments like "8 comments" are coming below new comment form . i have used mongodb . 

I do't know what wrong am i doing ? 

Please help me in this issue ..

Thanks a lot in advance ..

**Comment by XWB** [comment]
Closing as we don't have any MongoDB maintainers.
