### ISSUE TITLE
I need paged comments fos comment bundle as I can do ??

### ISSUE THREAD

**Issue by ebcamps** [FriendsOfSymfony/FOSCommentBundle#517]
I need paged comments fos comment bundle as I can do ??

**Comment by lookbadgers** [comment]
Yes but you would have to make it, see https://github.com/FriendsOfSymfony/FOSCommentBundle/blob/master/Resources/doc/10-other_ways_of_adding_comments_to_a_page.md

**Comment by XWB** [comment]
See comment above.
