### ISSUE TITLE
'fos_comment_submitted_form' trigger handler never called

### ISSUE THREAD

**Issue by Martin1982** [FriendsOfSymfony/FOSCommentBundle#523]
When posting a comment I want to handle the results with Javascript, there for I'm trying to hook into an  event with the following code;

`/**
     * Comment form submit complete
     */
    FOS_COMMENT.thread_container.on('fos_comment_submitted_form', function(data, statusCode){
        console.log('complete', data, statusCode);
    });`

It seems though that this eventhandler is never called, other event handlers like `fos_comment_show_form` are working just fine.

**Comment by Martin1982** [comment]
It seems to occur only when trying to handle errors or a comment on a comment.

**Comment by Martin1982** [comment]
Opened PR FriendsOfSymfony/FOSCommentBundle#524 to handle part of the problem

**Comment by XWB** [comment]
Fixed now.
