### ISSUE TITLE
Error in the post of comments

### ISSUE THREAD

**Issue by gastonrodriguezgr** [FriendsOfSymfony/FOSCommentBundle#525]
Hi

I have this problem: when I try to post a comment it failed and the post send this error:
Catchable Fatal Error: Argument 1 passed to FOS\CommentBundle\EventListener\CommentBlamerListener::__construct() must be an instance of Symfony\Component\Security\Core\SecurityContextInterface, instance of Symfony\Component\Security\Core\Authorization\AuthorizationChecker given, called in /my-root-folder/app/cache/dev/appDevDebugProjectContainer.php on line 1912 and defined

**Comment by tarjei** [comment]
Hi,
Which version of Symfony and CommentBundle are you running?

**Comment by XWB** [comment]
This was fixed in the latest master version.
