### ISSUE TITLE
Error with author hidrate

### ISSUE THREAD

**Issue by gastonrodriguezgr** [FriendsOfSymfony/FOSCommentBundle#526]
I have problem showing the authorName.

in the template comment_content.html.twig line 77 {{ comment.authorName }} this is not working.

i have the method getAuthorName() on Comment Class,
    public function getAuthorName(){
        if (null === $this->getAuthor()) {
            return 'Anonymous';
        }
        $fname      = $this->getAuthor()->getFirstName();
        $lname      = $this->getAuthor()->getLastName();
        $username   = $this->getAuthor()->getUsername();
        $retAuthor  = (!empty($fname)) ? $fname : $username;
        $retAuthor .= (!empty($fname) && !empty($lname)) ? ' '.$lname : '';

```
    return $retAuthor;
```

}

the problem is $this->author is only being hydrated with id. Here is a dump of the $this->author

UserBundle\Entity\User" ["**IS_PROXY**"]=> bool(true) ["**PROXY_INITIALIZED**"]=> bool(false) ["id"]=> string(4) "9487" ["firstName"]=> NULL ["lastName"]=> NULL ["birthday"]=> NULL ["dni"]=> NULL ["address"]=> NULL ["zipCode"]=> NULL ["phone"]=> NULL ["celPhone"]=> NULL ["urlFacebook"]=> NULL ["urlTwitter"]=> NULL ["twitterId"]=> NULL ["facebookId"]=> NULL ["userInfo"]=> NULL ["googleId"]=> NULL ["googlePlus"]=> NULL ["skype"]=> NULL ["gender"]=> NULL ["advertisements"]=> NULL ["comments"]=> NULL ["slug"]=> NULL ["created"]=> NULL ["updated"]=> NULL ["deletedAt"]=> NULL ["username"]=> NULL ["usernameCanonical"]=> NULL ["email"]=> NULL ["emailCanonical"]=> NULL ["enabled"]=> NULL ["salt"]=> NULL ["password"]=> NULL ["plainPassword"]=> NULL ["lastLogin"]=> NULL ["confirmationToken"]=> NULL ["passwordRequestedAt"]=> NULL ["groups"]=> NULL ["locked"]=> NULL ["expired"]=> NULL ["expiresAt"]=> NULL ["roles"]=> NULL ["credentialsExpired"]=> NULL ["credentialsExpireAt"]=> NULL }

**Comment by tdubuffet** [comment]
+1

**Comment by tdubuffet** [comment]
I have a solution.

To fix bug
`
parameters:
    fos_comment.manager.comment.default.class: FOS2CommentBundle\Entity\CommentManager
`

The CommentManager Override
`<?php
/**
 * Created by PhpStorm.
 * User: tdubuffet
 * Date: 30/08/16
 * Time: 18:00
 */

namespace FOS2CommentBundle\Entity;

use Doctrine\ORM\EntityManager;
use FOS\CommentBundle\Model\CommentManager as BaseCommentManager;
use FOS\CommentBundle\Model\ThreadInterface;
use FOS\CommentBundle\Model\CommentInterface;
use FOS\CommentBundle\Sorting\SortingFactory;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Doctrine\ORM\EntityRepository;

/**
 * Default ORM CommentManager.
 *
 * @author Tim Nagel <tim@nagel.com.au>
 */
class CommentManager extends \FOS\CommentBundle\Entity\CommentManager
{

    /**
     * {@inheritdoc}
     */
    public function findCommentsByThread(ThreadInterface $thread, $depth = null, $sorterAlias = null)
    {
        $qb = $this->repository
            ->createQueryBuilder('c')
            ->join('c.thread', 't')
            ->join('c.author', 'a') //Force hydrate
            ->where('t.id = :thread')
            ->orderBy('c.ancestors', 'ASC')
            ->setParameter('thread', $thread->getId());

        if (null !== $depth && $depth >= 0) {
            // Queries for an additional level so templates can determine
            // if the final 'depth' layer has children.

            $qb->andWhere('c.depth < :depth')
                ->setParameter('depth', $depth + 1);
        }

        $comments = $qb
            ->getQuery()
            ->execute();

        if (null !== $sorterAlias) {
            $sorter = $this->sortingFactory->getSorter($sorterAlias);
            $comments = $sorter->sortFlat($comments);
        }

        return $comments;
    }
}

`

**Comment by XWB** [comment]
The author should be lazy-loaded.
