### ISSUE TITLE
Performance issues at fos_comment_new_thread_comments

### ISSUE THREAD

**Issue by andrzejdziekonski** [FriendsOfSymfony/FOSCommentBundle#527]
Hi,

i have project running at Symfony 2.1 and have some performance dropdowns in fos_comment_new_thread_comments method. I attach my New Relic app monitor screenshot.
![newrelic2](https://cloud.githubusercontent.com/assets/2788843/14197739/2f9e132c-f7d2-11e5-875d-a20c40b9231c.jpg)
 . It looks like sometimes php-fpm spawns lots of childrens to deal with this action and i finally go out of RAM (no matter how much i reserve for php). 

I thought maybe its case of lack of search index and tried to add it in Thread Entity but schema update doesn't react for:
`* @ORM\Table(name="Thread", indexes = {@ORM\Index(name="search_idx",columns={"id", "permalink"})})`
Output says: "Nothing to update - your database is already in sync..." and when i add indexes manually and then update schema index is gone...

**Comment by tarjei** [comment]
Hi, there is not much to go on in your bugreport. Have you tried replicating this in your development environment?

**Comment by XWB** [comment]
Closing without further information.
