### ISSUE TITLE
FOSRestbundle 2.0

### ISSUE THREAD

**Issue by tarjei** [FriendsOfSymfony/FOSCommentBundle#528]
Hi, I started looking at FOSRestbundle 2.0 today. How should this be supported in CommentBundle?

The current dependency is on 1.6, but I'm using it with 1.7 without problems. 2.0 contains a lot of nice stuff so I would love to upgrade, but it will require at least Symfony 2.7 which implies that we will have to leave someone behind. 

What do you think? A separate 3.0 branch?

**Comment by tarjei** [comment]
See #530 for the changes needed. Not many, most are BC except the removal of Codes.

**Comment by XWB** [comment]
Fixed now.
