### ISSUE TITLE
Installation support for Symfony 3

### ISSUE THREAD

**Issue by sinclaireric** [FriendsOfSymfony/FOSCommentBundle#536]
hello. i want to install this bundle in symphony 3 But i havethis error
  - don't install symfony/validator v2.8.5|don't install symfony/symfony v3.0.6
    - don't install symfony/validator v2.8.6|don't install symfony/symfony v3.0.6
    - Installation request for symfony/symfony == 3.0.6.0 -> satisfiable by symfony/symfony[v3.0.6].

**Comment by Ener-Getick** [comment]
The support of symfony 3.0 isn't included in a stable release yet so you have to use the ``2.x-dev`` version of this bundle.
