### ISSUE TITLE
Bug with Symfony3.0 

### ISSUE THREAD

**Issue by zazoomauro** [FriendsOfSymfony/FOSCommentBundle#538]
`File Model/Vote.php`

`Symfony\Component\Validator\ExecutionContextInterface` doesn't exist anymore (Symfony 2.8.7 is the latest version of this file)

Clearing cache with warmup throws (_prod_ environment. With _dev_ environment works fine):
```
[Doctrine\Common\Proxy\Exception\UnexpectedValueException]                                                 
  The type hint of parameter "context" in method "isVoteValid" in class "Entity\Vote" is invalid.  
                                                                                                             
  [ReflectionException]                                                       
  Class Symfony\Component\Validator\ExecutionContextInterface does not exist
```

Tested in two different machines (mac(PHP5) and ubuntu(PHP7)). Same behaviour

**Comment by sinclaireric** [comment]
Please how to install ? I have posted an issue in #536

**Comment by zazoomauro** [comment]
@sinclaireric this issue is not related with the installation.

**Comment by Ener-Getick** [comment]
This issue seems related to doctrine itself. I'll see if i can do something.

**Comment by Ener-Getick** [comment]
I opened https://github.com/doctrine/common/pull/722 ;-)

**Comment by zazoomauro** [comment]
@Ener-Getick Thanks!

**Comment by Ocramius** [comment]
As commented in doctrine/common#722, this is a bug of THIS codebase.

**Comment by Ener-Getick** [comment]
Then maybe we should remove the type hint in ``Vote``. This would be a small BC break but I don't see a better solution...

**Comment by Ener-Getick** [comment]
This bug should only happen on php 5 (it should work on php7).
But it is enough important so that we can't release a new stable release before fixing this... as I said the easiest solution would be to remove the type hint, we just have to decide whether or not to do that.

**Comment by XWB** [comment]
I'm fine removing the type hint. Feel free to open a pull request.

**Comment by XWB** [comment]
@Ener-Getick Do you think you can make a PR? This would be the last change we need for a new release.

**Comment by Ener-Getick** [comment]
@XWB done, sorry I missed your answer.

**Comment by XWB** [comment]
@zazoomauro Can you try the latest master version and confirm if it works?

**Comment by zazoomauro** [comment]
@XWB Sure. I'll let you know ;-)

**Comment by XWB** [comment]
@zazoomauro Any updates?

**Comment by zazoomauro** [comment]
@XWB Sorry, holidays ;-)
Give me one day

**Comment by tdubuffet** [comment]
i try the latest master version, not work...

Solution:
<class name="FOS\CommentBundle\Model\Vote">
        <constraint name="Callback">isVoteValid</constraint>
    </class>

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSCommentBundle/commit/6a52d18d5ebeccfd2e00f9d13e71598124059310
