### ISSUE TITLE
Unexpected "render" tag (expecting closing tag for the "if" tag defined near line 17)

### ISSUE THREAD

**Issue by marvin-SL** [FriendsOfSymfony/FOSCommentBundle#544]
Hello, 

I installed this bundle on symfony 3.0.3.
On the profiler i've got this error when i try to load the page with comment zone
 `The template "FOSCommentBundle:Thread:comments.html.twig" contains an error: Unexpected "render" tag (expecting closing tag for the "if" tag defined near line 17) in "FOSCommentBundle:Thread:comments.html.twig" at line 17. `

In the related file I have 
`{% if depth == 0 %}
    {% if fos_comment_can_comment_thread(thread) %}
        {% render url("fos_comment_new_thread_comments", {"id": thread.id}) %}
    {% endif %}`

Is this a known issue ?
How to fix it ?

Thanks

**Comment by XWB** [comment]
This is wrong: `{{ render url(`. It should be `{{ render(url(`.

**Comment by marvin-SL** [comment]
Ok but i don't know why this line became like that after the installation of this bundle. 
I never edit the core of third party bundles. 
I did a fresh install and it works fine now.

Thanks
