### ISSUE TITLE
cant see comment form on Thred on symfony 3.1.2

### ISSUE THREAD

**Issue by simofes** [FriendsOfSymfony/FOSCommentBundle#547]
after installing the bundle
i configure it
so i see only 0 comments 
how can i post new comment?

grreetings
i am French

**Comment by simofes** [comment]
Please help me!!!!

**Comment by ashutoshrai1935** [comment]
I'm having the same issue.. please help

**Comment by ashutoshrai1935** [comment]
Hi,
I was having the same issue. 
check the entry in your thread table.
if it is having is_commentable as 0 you will not see the comments section.
you can set it to 1 or retry by truncating the table

**Comment by simofes** [comment]
Hi
Thank you
I execute a command on shell to set is_commentable to 1 for all article and finaly its work as well
Thank you
