### ISSUE TITLE
Vote it not working on Symfony 3.1.2

### ISSUE THREAD

**Issue by simofes** [FriendsOfSymfony/FOSCommentBundle#548]
after this command :
     php bin/console cache:clear -e=prod

 // Clearing the cache for the prod environment with debug false                                                        

                                                                                                            
  [Doctrine\Common\Proxy\Exception\UnexpectedValueException]                                                 
  The type hint of parameter "context" in method "isVoteValid" in class "AppBundle\Entity\Vote" is invalid.  
                                                                                                             

                                                                              
  [ReflectionException]                                                       
  Class Symfony\Component\Validator\ExecutionContextInterface does not exist

**Comment by simofes** [comment]
also after clicking in : 
xxxxx/web/app_dev.php/api/threads/111/comments/3/votes/new?value=1

i see the following error
{"methods":["isVoteValid"]} targeted by Callback constraint is not a valid callable

**Comment by simofes** [comment]
FIxed at [https://github.com/FriendsOfSymfony/FOSCommentBundle/issues/549](url)

**Comment by XWB** [comment]
Duplicate.
