### ISSUE TITLE
Get Vote working on symfony 3.1.2

### ISSUE THREAD

**Issue by simofes** [FriendsOfSymfony/FOSCommentBundle#549]
step 1)
   unComment line 64 in xxxxx\vendor\friendsofsymfony\comment-bundle\FOS\CommentBundle\Model\VoteInterface.php

                    `public function isValid(ExecutionContextInterface $context);`

step 2) delete lines from 52 to 57 : 
`    /**
     * @param LegacyExecutionContextInterface $context
     *
     * @deprecated since 2.1, to be removed in 3.0. Use {@link self::isValid()} instead.
     */
    public function isVoteValid(LegacyExecutionContextInterface $context);`

in xxxxx\vendor\friendsofsymfony\comment-bundle\FOS\CommentBundle\Model\Vote.php

step 3) delete line 17 : 
`use Symfony\Component\Validator\ExecutionContextInterface as LegacyExecutionContextInterface;`

step 4) delete line from 90 to 103:

    /**
     * {@inheritdoc}
     */
    public function isVoteValid(LegacyExecutionContextInterface $context)
    {
        if($context instanceof ExecutionContextInterface) {
            $this->isValid($context);
        } elseif (!$this->checkValue($this->value)) {
            $message = 'A vote cannot have a 0 value';
            $propertyPath = $context->getPropertyPath() . '.value';

            $context->addViolationAt($propertyPath, $message);
        }
    }

step 5) delete lines from 21 to 25 in xxxxx\vendor\friendsofsymfony\comment-bundle\FOS\CommentBundle\Tests\Fixtures\AbstractVote.php

`    /**
     * {@inheritdoc}
     */
    public function isVoteValid(LegacyExecutionContextInterface $context) {
    }`

step 6) delete lines from 31 to 35 in xxxxx\vendor\friendsofsymfony\comment-bundle\FOS\CommentBundle\Resources\config\validation.xml

replace there place by :  `<constraint name="Callback">isValid</constraint>`
some as following:
`    <class name="FOS\CommentBundle\Model\Vote">
        <constraint name="Callback">isValid</constraint>
    </class>`

step 7) clear cache for both envoronnement (dev & prod)
`       php bin/console cache:clear
       php bin/console cache:clear -e=prod`

finally Vote working 100%

![vote worked](https://cloud.githubusercontent.com/assets/5910836/16862408/fb79479e-4a40-11e6-8873-28c15678ce97.png)

Good by FOS friends

**Comment by XWB** [comment]
Please open a pull request.

**Comment by simofes** [comment]
How can i add a pull request i am new in GITUB
Thanks
