### ISSUE TITLE
Error in Symfony > 2.5

### ISSUE THREAD

**Issue by Filoz** [FriendsOfSymfony/FOSCommentBundle#555]
This commit https://github.com/FriendsOfSymfony/FOSCommentBundle/commit/ba54b4327b403748b359b9b139be1d58363f2266
removed
``` use Symfony\Component\Validator\Validator\ValidatorInterface; ```

That import is needed in Symfony > 2.5 and Symfony 3,  or the if ( https://github.com/FriendsOfSymfony/FOSCommentBundle/blob/master/Controller/ThreadController.php#L402 ) always fail.

I made a pull request to fix it https://github.com/FriendsOfSymfony/FOSCommentBundle/pull/554

**Comment by XWB** [comment]
Fixed in https://github.com/FriendsOfSymfony/FOSCommentBundle/pull/554
