### ISSUE TITLE
Time to cut a new release?

### ISSUE THREAD

**Issue by tarjei** [FriendsOfSymfony/FOSCommentBundle#560]
Hi, I would love to see a new release with the changes done to support FosRestBundle in it :)

**Comment by XWB** [comment]
Will work on a new release after https://github.com/FriendsOfSymfony/FOSCommentBundle/pull/559 :)

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSCommentBundle/releases/tag/v2.0.9

**Comment by tarjei** [comment]
Hi, - thanks. Is it possible to make the releasenotes a bit more informative?
