### ISSUE TITLE
Enabling full HTTPS/SSL with FOSCommentBundle

### ISSUE THREAD

**Issue by DHoogland** [FriendsOfSymfony/FOSCommentBundle#566]
When I try to enable full SSL on my website, FOSCommentBundle keeps posting comments to http://, and my site will redirect the request to https://, but won't post the comment anymore since its redirected.

I have tried setting the fos_comment_thread_api_base_url but that doesn't seem to help when posting comments.

Anyone a clue? Am I doing something wrong?

**Edit 1**: It might be Cloudflare that's getting the page from port 80 on the back-end, and showing it to the users on SSL/HTTPS (Flexible SSL)

**Comment by DHoogland** [comment]
It was indeed the webserver getting the request at port 80. Now I use FULL SSL it works fine!
Maybe it's still an option to add a HTTPS flag to the config to force that.

**Comment by psyray** [comment]
For those who have the same problem and using a reverse proxy (Traefik in my case), you must add the following code in your `public/index.php` (comment/uncomment your case)
Source : https://symfony.com/doc/current/deployment/proxies.html

```
// tell Symfony about your reverse proxy
Request::setTrustedProxies(
    // the IP address (or range) of your proxy
    ['172.18.0.0/8','192.0.0.1', '10.0.0.0/8'],
    
    // trust *all* "X-Forwarded-*" headers
    Request::HEADER_X_FORWARDED_ALL
    
    // or, if your proxy instead uses the "Forwarded" header
    // Request::HEADER_FORWARDED
    
    // or, if you're using AWS ELB
    //Request::HEADER_X_FORWARDED_AWS_ELB
    );

```
