### ISSUE TITLE
Ajax request issues with jQuery >= 3.0

### ISSUE THREAD

**Issue by shibby** [FriendsOfSymfony/FOSCommentBundle#572]
For $.get and $.post requests, .error and .complete functions removed on jQuery 3.0.

> The jqXHR.success(), jqXHR.error(), and jqXHR.complete() callback methods are removed as of jQuery 3.0. You can use jqXHR.done(), jqXHR.fail(), and jqXHR.always() instead.

Bcs of that on [comments.js](https://github.com/FriendsOfSymfony/FOSCommentBundle/blob/master/Resources/public/js/comments.js) 
`$.get(url, data, success).error(wrappedErrorCallback);` should change as 
`$.get(url, data, success).fail(wrappedErrorCallback);` and as same as $.post function. 

BUT, i have no idea for what happens if jQuery version lower than 3.0. Maybe you can do a jQuery version check?

**Comment by XWB** [comment]
@shibby  I bumped master to 3.0.x-dev, we can make it jQuery 3 compatible.

**Comment by XWB** [comment]
@shibby Can you have a look at https://github.com/FriendsOfSymfony/FOSCommentBundle/pull/590 ?

**Comment by shibby** [comment]
@XWB great, thanks :)
So, FOSCommentBundle will release next version 3.0.x right? Then we don't need to think about BC :)

**Comment by XWB** [comment]
Indeed :)

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSCommentBundle/pull/590
