### ISSUE TITLE
Question: Documenting use with FOSRestBundle

### ISSUE THREAD

**Issue by jandom** [FriendsOfSymfony/FOSCommentBundle#575]
hi guys, 

this library is decoupled from the fos rest bundle, as mentioned in this issue

This is related to https://github.com/FriendsOfSymfony/FOSCommentBundle/issues/352

that said, it's a fairly popular use case – would it make sense to put together a tutorial on how to use the FOSCommentBundle and FOSRestBundle together? 

It took me a while to figure it out and i could save people some time in the future. What I'm thinking about is some basic cURL requests examples to do basic crud on threads/comment. 

Would such contribution be helpful?

**Comment by XWB** [comment]
> Would such contribution be helpful?

Additional documentation is always helpful :) Feel free to open a PR.
