### ISSUE TITLE
fos_comment_get_threads: unable to  find template ""

### ISSUE THREAD

**Issue by arodiss** [FriendsOfSymfony/FOSCommentBundle#578]
Hello and thank you for creating this awesome bundle.

I attached it to my project without even understanding what all this means and magically everything works - really impressive.
However, in logs sometimes I see error like this
```
Matched route "fos_comment_get_threads" (...)
Route parameters: (...) _format: html (...)
Unable to find template "" (...)

(in stacktrace section)
at TwigEngine ->load (null) 
at TwigEngine ->render (null, array('threads' => array())) 
at ViewHandler ->renderTemplate (object(View), 'html') 
(...)
```
I called URL `/api/threads.html` in browser directly and see this error indeed.
Have no idea where this request comes from - as I said, actual functionality is working for me
But looks like the problem is that `ThreadController::getThreadsActions()` (shouldn't it be "action" without "s"?) does not call `$view->setTemplate()` which is OK for JSON but not OK for HTML

**Comment by arodiss** [comment]
I worked around this issue by adding following to my `config.yml` (notice that I don't use FOS Rest Bundle directly, it is provided via FOS Comment):
```
fos_rest:
    view:
        templating_formats:
            html: false
    format_listener:
        rules:
            fallback_format: json
```
Now I have proper JSON 404 when calling `/api/threads.html` and proper JSON 200 when calling `/api/threads`

Still, bundle behavior seems weird - it does not provide HTML version of content but allows to ask for it, which results in 404 error

**Comment by XWB** [comment]
Seems related to FOSRestBundle configuration, see https://stackoverflow.com/questions/18010784/fos-rest-bundle-unable-to-find-template
