### ISSUE TITLE
How to differentiate from triggered events if a comment is being created, updated or deleted? 

### ISSUE THREAD

**Issue by victorbstan** [FriendsOfSymfony/FOSCommentBundle#588]
I'm hooking into the `COMMENT_POST_PERSIST` event, but this event fires for new, updated, or deleted comments. How can I detect what state a message is at in an event, or hook into an event based on these 3 states of a message? I have noticed that comments have a `state` attribute, which is 0 for new messages, 0 for updated messages and 1 for deleted messages... not sure if this is a coincidence or if it truly is part of some message status flag.

**Comment by XWB** [comment]
Inject the `CommentManager` and use the `isNewComment` method.

https://github.com/FriendsOfSymfony/FOSCommentBundle/blob/master/Entity/CommentManager.php#L151

**Comment by victorbstan** [comment]
Thanks, is this how the comment manager is referenced? `fos_comment.manager.comment.default.class`

**Comment by XWB** [comment]
You will need to use the `COMMENT_PRE_PERSIST` event. The `isNewComment` method can only return `true` when a comment has no `id`. Once you persist a new comment, it will have a `id`.

**Comment by victorbstan** [comment]
Thanks, ultimately, I needed some extra information about the creator of the comment, which isn't available by default in the PRE_PERSIST event, but got around this by adding a `updated_at` column to comments, and checking the diff between the `created_at` and `updated_at` dates to verify new, vs edited comments. Wondering if it wouldn't have been nice of an `updated_at` column existed by default, as I personally think that's a nice thing to have on any db row that can be updated.

**Comment by XWB** [comment]
:+1:
