### ISSUE TITLE
Overriding Thread Controller(add custom logic)

### ISSUE THREAD

**Issue by zettsu** [FriendsOfSymfony/FOSCommentBundle#601]
Hi sorry for comment here don't know where to post my issue I have questions for how to override some methods of /api, in order to add logic and other validations for custom fields. Controller, in particular, is ThreadController I tried to do according to doc but it's not working
You can give me a starting point for this, I read the documentation for Symfony2 http://symfony.com/doc/2.3/cookbook/bundles/inheritance.html, but this doesn't work for this bundle. Thanks and sorry for bad English

**Comment by XWB** [comment]
Issue is not related to FOSCommentBundle, though you might get some answers at stackoverflow.
