### ISSUE TITLE
javascript, jquery problem

### ISSUE THREAD

**Issue by nansnans** [FriendsOfSymfony/FOSCommentBundle#604]
Hello,

I'm trying to display my form comment on a page.
I've got an issue in my console : 
comments.js:85 Uncaught TypeError: $.get(...).error is not a function
    at Object.get (comments.js:85)
    at Object.getThreadComments (comments.js:103)
    at comments.js:525
    at comments.js:540

I don't know how can i fix it.

(i've got jquery 3.2.1)
Can you help me ?

Thank you very much

**Comment by flim** [comment]
Same happened to me. Using jQuery 3.2.1 and Symfony 3

**Comment by iBasit** [comment]
same to me +1

**Comment by iBasit** [comment]
did anyone figured this out?

**Comment by iBasit** [comment]
still no support!!!

**Comment by iBasit** [comment]
> The jqXHR.success(), jqXHR.error(), and jqXHR.complete() callback methods are removed as of jQuery 3.0. You can use jqXHR.done(), jqXHR.fail(), and jqXHR.always() instead.

**Comment by iBasit** [comment]
To support `jQuery 3.*`

from
`            $.post(url, data, success).error(wrappedErrorCallback).complete(wrappedCompleteCallback);
`
to 

`            $.post(url, data, success).fail(wrappedErrorCallback).done(wrappedCompleteCallback);
`

from 

`            $.get(url, data, success).error(wrappedErrorCallback);
`

to 

`            $.get(url, data, success).fail(wrappedErrorCallback);
`

**Comment by XWB** [comment]
This was fixed in master branch several months ago: https://github.com/FriendsOfSymfony/FOSCommentBundle/commit/c721064c8f598be97c36a959e910a78a27ff670e

**Comment by flim** [comment]
Ok i got it.
We have to use the master branch and use **jquery.min.js** and not **jquery.slim.js**

**Comment by YanisDbz** [comment]
I already use **jquery.min.js** but always the same problem ...

**Comment by KhanMaytok** [comment]
I have to use Jquery1.10.x to get away the problem

**Comment by VarukVlad** [comment]
I did like KhanMaytok. And solved problem.

**Comment by XWB** [comment]
Will tag FOSCommentBundle 3.0 before the end of the year.
