### ISSUE TITLE
JMSSerializerBundle 2.0.0 incompatibility

### ISSUE THREAD

**Issue by sss71** [FriendsOfSymfony/FOSCommentBundle#608]
FOSCommentBundle version 2.x is incompaitible with the latest version of JMSSerializerBundle .
When trying to install FOSCommentBundle on my current config I got error:

`php composer.phar require friendsofsymfony/comment-bundle
Using version ^2.0 for friendsofsymfony/comment-bundle
...
  Problem 1
    - friendsofsymfony/comment-bundle v2.0.9 requires jms/serializer-bundle ~0.11|~1.0 -> satisfiable by jms/serializer-bundle[0.11.0, 0.12.0, 0.13.0, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.5.0] but these conflict with your requirements or minimum-stability.
`

In my project I am using JMSSerializerBundle 2.0 released on May 17.  As is said on its homepage:

> The 2.0.0 release in almost fully backward compatible with the 1.x branch. (...) There are no new features in the 2.0.0 release compared to 1.5.0. The 2.0.0 release has the main goal of changing some configuration defaults, that in most of the cases bring performance improvements or improve the DX by providing a better error handling and a more predictable application behaviour.

I could downgrade JMSSerializerBundle to 1.5, or use FOSCommentBundle in dev version (comment-bundle:3.0.x-dev works with JMSSerializerBundle 2.0) but both this workaround doesn't meet my requirements.

Are you planing to upgrade FOSCommentBundle soon?

**Comment by XWB** [comment]
Will tag FOSCommentBundle 3.0 before the end of the year.
