### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by peyman-mohamadpour** [FriendsOfSymfony/FOSCommentBundle#622]
in [Step 6: Integration with FOSUserBundle](https://github.com/FriendsOfSymfony/FOSCommentBundle/blob/master/Resources/doc/6-integration_with_fosuserbundle.md) on **Setup FOSUserBundle** section, the link to 

Check the [instructions]
https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/doc/index.md

seams to be dead.

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSCommentBundle/commit/fd8abd6b6e8a38366bcc58f835b35b91db775417
