### ISSUE TITLE
URL Validator should not be runned against decoded permalink

### ISSUE THREAD

**Issue by nreynis** [FriendsOfSymfony/FOSCommentBundle#638]
When creating a new thread the permalink URL is decoded before being stored:

[ThreadController->getThreadCommentsAction](https://github.com/FriendsOfSymfony/FOSCommentBundle/blob/master/Controller/ThreadController.php#L396)
```php
// Decode the permalink for cleaner storage (it is encoded on the client side)
$permalink = urldecode($request->query->get('permalink'));
```
The problem is that after decoding it, the URLValidator is runned. The validator will then fail because the URL contains special characters which should have been encoded:

[ThreadController->getThreadCommentsAction](https://github.com/FriendsOfSymfony/FOSCommentBundle/blob/master/Controller/ThreadController.php#L405)
```php
if ($validator instanceof ValidatorInterface) {
    $errors = $validator->validate($thread, null, array('NewThread'));
} else {
    $errors = $validator->validate($thread, array('NewThread'));
}
```

**Comment by XWB** [comment]
Fixed in https://github.com/FriendsOfSymfony/FOSCommentBundle/pull/646
